---
# Source: stakater-external-secrets/charts/external-secrets/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-external-secrets
  namespace: "default"
  labels:
    helm.sh/chart: external-secrets-0.3.14
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.3.11"
    app.kubernetes.io/managed-by: Helm
---
# Source: stakater-external-secrets/charts/external-secrets/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-external-secrets-controller
  labels:
    helm.sh/chart: external-secrets-0.3.14
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.3.11"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
    - "external-secrets.io"
    resources:
    - "secretstores"
    - "clustersecretstores"
    - "externalsecrets"
    verbs:
    - "get"
    - "list"
    - "watch"
  - apiGroups:
    - "external-secrets.io"
    resources:
    - "externalsecrets"
    - "externalsecrets/status"
    - "externalsecrets/finalizers"
    verbs:
    - "update"
    - "patch"
  - apiGroups:
    - ""
    resources:
    - "serviceaccounts"
    verbs:
    - "get"
    - "list"
    - "watch"
  - apiGroups:
    - ""
    resources:
    - "configmaps"
    verbs:
    - "get"
    - "list"
    - "watch"
  - apiGroups:
    - ""
    resources:
    - "secrets"
    verbs:
    - "get"
    - "list"
    - "watch"
    - "create"
    - "update"
    - "delete"
    - "patch"
  - apiGroups:
    - ""
    resources:
    - "serviceaccounts/token"
    verbs:
    - "create"
  - apiGroups:
    - ""
    resources:
    - "events"
    verbs:
    - "create"
    - "patch"
---
# Source: stakater-external-secrets/charts/external-secrets/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-external-secrets-view
  labels:
    helm.sh/chart: external-secrets-0.3.14
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.3.11"
    app.kubernetes.io/managed-by: Helm
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - "external-secrets.io"
    resources:
      - "externalsecrets"
      - "secretstores"
      - "clustersecretstores"
    verbs:
      - "get"
      - "watch"
      - "list"
---
# Source: stakater-external-secrets/charts/external-secrets/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-external-secrets-edit
  labels:
    helm.sh/chart: external-secrets-0.3.14
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.3.11"
    app.kubernetes.io/managed-by: Helm
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - "external-secrets.io"
    resources:
      - "externalsecrets"
      - "secretstores"
      - "clustersecretstores"
    verbs:
      - "create"
      - "delete"
      - "deletecollection"
      - "patch"
      - "update"
---
# Source: stakater-external-secrets/charts/external-secrets/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-name-external-secrets-controller
  labels:
    helm.sh/chart: external-secrets-0.3.14
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.3.11"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-external-secrets-controller
subjects:
  - name: release-name-external-secrets
    namespace: "default"
    kind: ServiceAccount
---
# Source: stakater-external-secrets/charts/external-secrets/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-external-secrets-leaderelection
  namespace: "default"
  labels:
    helm.sh/chart: external-secrets-0.3.14
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.3.11"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
    - ""
    resources:
    - "configmaps"
    resourceNames:
    - "external-secrets-controller"
    verbs:
    - "get"
    - "update"
    - "patch"
  - apiGroups:
    - ""
    resources:
    - "configmaps"
    verbs:
    - "create"
  - apiGroups:
    - "coordination.k8s.io"
    resources:
    - "leases"
    verbs:
    - "get"
    - "create"
    - "update"
    - "patch"
---
# Source: stakater-external-secrets/charts/external-secrets/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-external-secrets-leaderelection
  namespace: "default"
  labels:
    helm.sh/chart: external-secrets-0.3.14
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.3.11"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-external-secrets-leaderelection
subjects:
  - kind: ServiceAccount
    name: release-name-external-secrets
    namespace: "default"
---
# Source: stakater-external-secrets/charts/external-secrets/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-external-secrets-metrics
  labels:
    helm.sh/chart: external-secrets-0.3.14
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.3.11"
    app.kubernetes.io/managed-by: Helm
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: prometheus
      name: prometheus
      protocol: TCP
  selector:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
---
# Source: stakater-external-secrets/charts/external-secrets/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-external-secrets
  namespace: "default"
  labels:
    helm.sh/chart: external-secrets-0.3.14
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.3.11"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-secrets
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-external-secrets
      containers:
        - name: external-secrets
          image: "ghcr.io/external-secrets/external-secrets:v0.3.11"
          imagePullPolicy: IfNotPresent
          args:
          - --concurrent=1
          ports:
            - containerPort: 8080
              name: prometheus
              protocol: TCP
---
# Source: stakater-external-secrets/charts/external-secrets/templates/servicemonitor.yaml
apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  name: release-name-external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    helm.sh/chart: external-secrets-0.3.14
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  endpoints:
  - interval: 
    port: prometheus
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
